[paths]
output = "shost"
source = [".", "Polyweb", "Polyweb/Polynet"]
artifact = "obj"
install = "/usr/local/bin"

[options]
compilation-flags = "-Wall -std=c++17 -O3 -pthread"
libraries = ["boost_program_options", "ssl", "crypto"]

[env.OS.Windows_NT.paths]
library = ["\"$(BOOST_ROOT)\"/stage/lib", "\"$(OPENSSL_ROOT_DIR)\"/lib"]
install = "C:\\Windows\\System32"

[env.OS.Windows_NT.options]
compilation-flags = "/W3 /std:c++20 /EHsc /I\"$(BOOST_ROOT)\" /I\"$(OPENSSL_ROOT_DIR)\"/include /Ox"
libraries = ["libssl.lib", "libcrypto.lib", "advapi32.lib", "crypt32.lib", "ws2_32.lib", "user32.lib"]

[env.OS.Darwin.options]
libraries = ["boost_program_options-mt", "ssl", "crypto"]
